clearance_hw:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - linear_motor_cursor_joint
  - ur5_shoulder_pan_joint
  - ur5_shoulder_lift_joint
  - ur5_elbow_joint
  - ur5_wrist_1_joint
  - ur5_wrist_2_joint
  - ur5_wrist_3_joint
  - Belly_rotx
  - Belly_roty
  - jRightShoulder_rotx
  - jRightShoulder_roty
  - jRightShoulder_rotz
  - jRightElbow_rotz
  - jRightWristRoll
  - jRightWristPitch
  - jRightWristYaw
  - jLeftShoulder_rotx
  - jLeftShoulder_roty
  - jLeftShoulder_rotz
  - jLeftElbow_rotz
  - joint_traslx
  - joint_trasly
  - joint_orientation

  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/joint_states"
  command_joint_state_topic: "/joint_pos_target"
  sampling_period: 0.008
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/clearance_hw/ur5_task_joint_scaling/follow_joint_trajectory/cancel"
  - "/clearance_hw/ur5_task_joint_scaling/follow_joint_trajectory/feedback"
  - "/clearance_hw/ur5_task_joint_scaling/follow_joint_trajectory/goal"
  - "/clearance_hw/ur5_task_joint_scaling/follow_joint_trajectory/result"
  - "/clearance_hw/ur5_task_joint_scaling/follow_joint_trajectory/status"

  - "/clearance_hw/ur5_task_clearance_scaling/follow_joint_trajectory/cancel"
  - "/clearance_hw/ur5_task_clearance_scaling/follow_joint_trajectory/feedback"
  - "/clearance_hw/ur5_task_clearance_scaling/follow_joint_trajectory/goal"
  - "/clearance_hw/ur5_task_clearance_scaling/follow_joint_trajectory/result"
  - "/clearance_hw/ur5_task_clearance_scaling/follow_joint_trajectory/status"

  - "/clearance_hw/ur5_task_joint_ssm/follow_joint_trajectory/cancel"
  - "/clearance_hw/ur5_task_joint_ssm/follow_joint_trajectory/feedback"
  - "/clearance_hw/ur5_task_joint_ssm/follow_joint_trajectory/goal"
  - "/clearance_hw/ur5_task_joint_ssm/follow_joint_trajectory/result"
  - "/clearance_hw/ur5_task_joint_ssm/follow_joint_trajectory/status"

  - "/clearance_hw/ur5_thor_impedance/follow_joint_trajectory/cancel"
  - "/clearance_hw/ur5_thor_impedance/follow_joint_trajectory/feedback"
  - "/clearance_hw/ur5_thor_impedance/follow_joint_trajectory/goal"
  - "/clearance_hw/ur5_thor_impedance/follow_joint_trajectory/result"
  - "/clearance_hw/ur5_thor_impedance/follow_joint_trajectory/status"

  remap_target_args:
  - "/ur5_on_guide/follow_joint_trajectory/cancel"
  - "/ur5_on_guide/follow_joint_trajectory/feedback"
  - "/ur5_on_guide/follow_joint_trajectory/goal"
  - "/ur5_on_guide/follow_joint_trajectory/result"
  - "/ur5_on_guide/follow_joint_trajectory/status"

  - "/ur5_on_guide/follow_joint_trajectory/cancel"
  - "/ur5_on_guide/follow_joint_trajectory/feedback"
  - "/ur5_on_guide/follow_joint_trajectory/goal"
  - "/ur5_on_guide/follow_joint_trajectory/result"
  - "/ur5_on_guide/follow_joint_trajectory/status"

  - "/ur5_on_guide/follow_joint_trajectory/cancel"
  - "/ur5_on_guide/follow_joint_trajectory/feedback"
  - "/ur5_on_guide/follow_joint_trajectory/goal"
  - "/ur5_on_guide/follow_joint_trajectory/result"
  - "/ur5_on_guide/follow_joint_trajectory/status"

  - "/ur5_on_guide/follow_joint_trajectory/cancel"
  - "/ur5_on_guide/follow_joint_trajectory/feedback"
  - "/ur5_on_guide/follow_joint_trajectory/goal"
  - "/ur5_on_guide/follow_joint_trajectory/result"
  - "/ur5_on_guide/follow_joint_trajectory/status"

  ur5_task_joint_scaling:
    type: "taskQP/TaskBasedPosController"
    controlled_joint:
    - linear_motor_cursor_joint
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint

    spline_order: 1
    control_horizon: 0.2
    prediction_size: 5
    clik_gain: 100

  ur5_task_clearance_scaling:
    type: "taskQP/TaskClearancePosVelEffController"
    controlled_joint:
    - linear_motor_cursor_joint
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint

    spline_order: 1
    control_horizon: 0.2
    prediction_size: 5
    clik_gain: 100
    selection_axis: [1, 1, 1, 1, 1, 1]
    base_frame: "world"
    tool_frame: "tip"
    elbow_frame: "ur5_forearm_link"
    clearance_gain: 0.5
    use_smooth_swap: true
    delta_q_ref: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
    use_delta_q_max: true
    use_delta_q_min: true
    delta_q_max: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
    clearance_activation_threshold: 1.4
    slowdown_distance: 1.2
    stop_distance: 0.4
    clearance_gain: 0.4

  ur5_task_joint_ssm:
    type: "taskQP/TaskJointSSMPosVelEffController"
    controlled_joint:
    - linear_motor_cursor_joint
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint

    spline_order: 1
    control_horizon: 0.2
    prediction_size: 5
    clik_gain: 100
    base_frame: "world"
    tool_frame: "ur5_tool0"
    elbow_frame: "ur5_forearm_link"

  ur5_thor_impedance:
    type: "taskQP/ThorImpedancePosVelEffController"
    controlled_joint:
    - linear_motor_cursor_joint
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint

    spline_order: 1
    control_horizon: 0.2
    prediction_size: 5
    clik_gain: 10
    base_frame: "world"
    tool_frame: "ur5_tool0"
    elbow_frame: "ur5_forearm_link"
    inertia: 2.0
    stiffness: 0.0
    damping: 20.0
    
