mao_hw:
  type: "itia/control/FakeHwIfaceNodelet"
  joint_names:
  - Belly_rotx
  - Belly_roty
  - jRightShoulder_rotx
  - jRightShoulder_roty
  - jRightShoulder_rotz
  - jRightElbow_rotz
  - jRightWristRoll
  - jRightWristPitch
  - jRightWristYaw
  - jLeftShoulder_rotx
  - jLeftShoulder_roty
  - jLeftShoulder_rotz
  - jLeftElbow_rotz
  - joint_traslx
  - joint_trasly
  - joint_orientation
  allowed_controller_types:
  - "controller_type1"
  diagnostic_period: 0.1
  sampling_period: 0.008

  remap_source_args:
  - "/mao_hw/js_pub/joint_states"
  remap_target_args:
  - "/mao/joint_states"


  initial_position: [9.105649827979505e-05, 3.35796186234802e-05, 0.008796351798018439, 0.3385418147488032, 0.7506488721689676, 0.8764253956129309, 0.36453462007460186, -0.01736111295665614, -0.15622582588633524, -1.2756961155408528, 1.352749709039926e-05, -9.380312701687217e-05, -7.660039092879742e-05, 0.05514946264894679, 8.042699191719349e-07, -9.105743253603578e-05]

  js_pub:
    type:         ros/control/JointStatePublisher
    controlled_joint:
    - Belly_rotx
    - Belly_roty
    - jRightShoulder_rotx
    - jRightShoulder_roty
    - jRightShoulder_rotz
    - jRightElbow_rotz
    - jRightWristRoll
    - jRightWristPitch
    - jRightWristYaw
    - jLeftShoulder_rotx
    - jLeftShoulder_roty
    - jLeftShoulder_rotz
    - jLeftElbow_rotz
    - joint_traslx
    - joint_trasly
    - joint_orientation
  ctrl1:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "Belly_rotx"

  ctrl2:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "Belly_roty"

  ctrl3:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jRightShoulder_rotx"

  ctrl4:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jRightShoulder_roty"

  ctrl5:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jRightShoulder_rotz"

  ctrl6:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jRightElbow_rotz"

  ctrl7:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jRightWristRoll"

  ctrl8:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jRightWristPitch"

  ctrl9:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jRightWristYaw"

  ctrl10:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jLeftShoulder_rotx"

  ctrl11:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jLeftShoulder_roty"

  ctrl12:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jLeftShoulder_rotz"

  ctrl13:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "jLeftElbow_rotz"

  ctrl14:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "joint_traslx"

  ctrl15:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "joint_trasly"
  ctrl16:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "joint_orientation"

ur5_hw:
  type: "itia/control/FakeHwIfaceNodelet"
  joint_names:
  - ur5_shoulder_pan_joint
  - ur5_shoulder_lift_joint
  - ur5_elbow_joint
  - ur5_wrist_1_joint
  - ur5_wrist_2_joint
  - ur5_wrist_3_joint
  allowed_controller_types:
  - "controller_type1"
  diagnostic_period: 0.1
  sampling_period: 0.008

  initial_position: [0, -1.57, 0, 0, 0, 0]
  remap_source_args:
  - "/ur5_hw/js_pub/joint_states"
  remap_target_args:
  - "/ur5/joint_states"

  js_pub:
    type:         ros/control/JointStatePublisher
    controlled_joint:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint

  linkpos_to_vel_jnt1:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "ur5_shoulder_pan_joint"

  linkpos_to_vel_jnt2:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "ur5_shoulder_lift_joint"

  linkpos_to_vel_jnt3:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "ur5_elbow_joint"

  linkpos_to_vel_jnt4:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "ur5_wrist_1_joint"

  linkpos_to_vel_jnt5:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "ur5_wrist_2_joint"

  linkpos_to_vel_jnt6:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "ur5_wrist_3_joint"

coe_hw:
  type: "itia/control/FakeHwIfaceNodelet"
  joint_names:
  - linear_motor_cursor_joint

  remap_source_args:
  - "/coe_hw/js_pub/joint_states"
  remap_target_args:
  - "/elmo/joint_states"

  js_pub:
    type: ros/control/JointStatePublisher
    controlled_joint:
    - linear_motor_cursor_joint

  linkpos_to_vel_jnt0:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/joint_pos_target"
    controlled_joint: "linear_motor_cursor_joint"

