mao_planner_hw:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - Belly_rotx
  - Belly_roty
  - jRightShoulder_rotx
  - jRightShoulder_roty
  - jRightShoulder_rotz
  - jRightElbow_rotz
  - jRightWristRoll
  - jRightWristPitch
  - jRightWristYaw
  - jLeftShoulder_rotx
  - jLeftShoulder_roty
  - jLeftShoulder_rotz
  - jLeftElbow_rotz
  - joint_traslx
  - joint_trasly
  - joint_orientation

  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/mao/joint_states"
  command_joint_state_topic: "/mao/joint_pos_target"
  sampling_period: 0.008
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/mao_planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/mao_planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/mao_planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/mao_planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/mao_planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/status"
  - "/mao_planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/mao_planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/mao_planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/mao_planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/mao_planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/status"
  - "/mao_planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/mao_planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/mao_planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/mao_planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/mao_planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/status"


  remap_target_args:

  - "/human_right_arm/follow_joint_trajectory/cancel"
  - "/human_right_arm/follow_joint_trajectory/feedback"
  - "/human_right_arm/follow_joint_trajectory/goal"
  - "/human_right_arm/follow_joint_trajectory/result"
  - "/human_right_arm/follow_joint_trajectory/status"

  - "/human_left_arm/follow_joint_trajectory/cancel"
  - "/human_left_arm/follow_joint_trajectory/feedback"
  - "/human_left_arm/follow_joint_trajectory/goal"
  - "/human_left_arm/follow_joint_trajectory/result"
  - "/human_left_arm/follow_joint_trajectory/status"

  - "/human_torso/follow_joint_trajectory/cancel"
  - "/human_torso/follow_joint_trajectory/feedback"
  - "/human_torso/follow_joint_trajectory/goal"
  - "/human_torso/follow_joint_trajectory/result"
  - "/human_torso/follow_joint_trajectory/status"

  human_right_arm_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - Belly_rotx
    - Belly_roty
    - jRightShoulder_rotx
    - jRightShoulder_roty
    - jRightShoulder_rotz
    - jRightElbow_rotz
    - jRightWristRoll
    - jRightWristPitch
    - jRightWristYaw
    - joint_traslx
    - joint_trasly
    - joint_orientation
    spline_order: 1
  human_left_arm_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - jLeftShoulder_rotx
    - jLeftShoulder_roty
    - jLeftShoulder_rotz
    - jLeftElbow_rotz
    spline_order: 1

  human_torso_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - Belly_rotx
    - Belly_roty
    - joint_traslx
    - joint_trasly
    - joint_orientation
    spline_order: 1

