planner_hw:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - linear_motor_cursor_joint
  - ur5_shoulder_pan_joint
  - ur5_shoulder_lift_joint
  - ur5_elbow_joint
  - ur5_wrist_1_joint
  - ur5_wrist_2_joint
  - ur5_wrist_3_joint
  - Belly_rotx
  - Belly_roty
  - jRightShoulder_rotx
  - jRightShoulder_roty
  - jRightShoulder_rotz
  - jRightElbow_rotz
  - jRightWristRoll
  - jRightWristPitch
  - jRightWristYaw
  - jLeftShoulder_rotx
  - jLeftShoulder_roty
  - jLeftShoulder_rotz
  - jLeftElbow_rotz
  - joint_traslx
  - joint_trasly
  - joint_orientation

  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/joint_states"
  command_joint_state_topic: "/joint_pos_target"
  sampling_period: 0.008
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/planner_hw/ur5_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/planner_hw/ur5_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/planner_hw/ur5_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/planner_hw/ur5_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/planner_hw/ur5_thor_prefilter_planner/follow_joint_trajectory/status"

  - "/planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/planner_hw/human_right_arm_thor_prefilter_planner/follow_joint_trajectory/status"

  - "/planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/planner_hw/human_left_arm_thor_prefilter_planner/follow_joint_trajectory/status"

  - "/planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/planner_hw/human_torso_thor_prefilter_planner/follow_joint_trajectory/status"

  remap_target_args:
  - "/ur5_on_guide/follow_joint_trajectory/cancel"
  - "/ur5_on_guide/follow_joint_trajectory/feedback"
  - "/ur5_on_guide/follow_joint_trajectory/goal"
  - "/ur5_on_guide/follow_joint_trajectory/result"
  - "/ur5_on_guide/follow_joint_trajectory/status"

  - "/human_right_arm/follow_joint_trajectory/cancel"
  - "/human_right_arm/follow_joint_trajectory/feedback"
  - "/human_right_arm/follow_joint_trajectory/goal"
  - "/human_right_arm/follow_joint_trajectory/result"
  - "/human_right_arm/follow_joint_trajectory/status"

  - "/human_left_arm/follow_joint_trajectory/cancel"
  - "/human_left_arm/follow_joint_trajectory/feedback"
  - "/human_left_arm/follow_joint_trajectory/goal"
  - "/human_left_arm/follow_joint_trajectory/result"
  - "/human_left_arm/follow_joint_trajectory/status"

  - "/human_torso/follow_joint_trajectory/cancel"
  - "/human_torso/follow_joint_trajectory/feedback"
  - "/human_torso/follow_joint_trajectory/goal"
  - "/human_torso/follow_joint_trajectory/result"
  - "/human_torso/follow_joint_trajectory/status"

  ur5_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - linear_motor_cursor_joint
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
    spline_order: 1
  human_right_arm_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    overrides:
    - /mao_ovr1
    - /mao_ovr2

    controlled_joint:
    - joint_traslx
    - joint_trasly
    - Belly_rotx
    - Belly_roty
    - joint_orientation
    - jRightShoulder_rotx
    - jRightShoulder_roty
    - jRightShoulder_rotz
    - jRightElbow_rotz
    - jRightWristRoll
    - jRightWristPitch
    - jRightWristYaw

    spline_order: 1
  human_left_arm_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - jLeftShoulder_rotx
    - jLeftShoulder_roty
    - jLeftShoulder_rotz
    - jLeftElbow_rotz
    spline_order: 1
  human_torso_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - Belly_rotx
    - Belly_roty
    - joint_traslx
    - joint_trasly
    - joint_orientation
    spline_order: 1
