lastra    : {box: [1, 0.01, 1], color: [0.4,0.9,0.9,1]} # color Red,Green,Blue,Alpha
palo    : {box: [0.2, 0.2, 2], color: [0.7,0,0,1]} # color Red,Green,Blue,Alpha

scene_objects:
#- {type: "lastra", frame: "world", position: [1.5, -0.54 ,1.5], quaternion: [0, 0, 0, 1]}
- {type: "palo", frame: "world", position: [1, -0.6 ,1], quaternion: [0, 0, 0, 1]}





