# mongo_database: "test_mosaic"
# mongo_collection_tasks: "tasks_properties"
# mongo_collection_results: "dummy_results"
# coll_risk_name: "dummy_risks"
# coll_duration_name: "dummy_durations"

# mongo_database: "agents_synergy"
# mongo_collection_tasks: "tasks_properties_test"
# mongo_collection_results: "sinergy_results_test_long"
#
# coll_risk_name: "dynamics_long_test_outliers_3"
# coll_duration_name: durations_long


# # ### Stavo usando questi
# mongo_database: "milp_task_planner"
# mongo_collection_tasks: "task_properties"
# # mongo_collection_results: "task_results"
# mongo_collection_results: "task_results_areas"
#
# coll_duration_name: "task_durations"
# coll_risk_name: "task_synergies_bayesian"
# # coll_risk_name: "task_synergies"
# # ### Fino qui usando questi

# ------------------------------------------------------
## SAFETY AREAS BOTH AGENTS
mongo_database: "safety_areas"
mongo_collection_tasks: "task_properties"
# mongo_collection_results: "task_results"
# mongo_collection_results: "task_results_ha"
# mongo_collection_results: "task_results_scaling"
mongo_collection_results: "task_results_online_phase"
coll_duration_name: "task_durations"
# coll_risk_name: "task_synergies"
coll_risk_name: "task_synergies_bayesian"
# ---------------------------------------------------------

# ## WORKSTATION COMPARISON
# mongo_database: "workstation_comparison"
# mongo_collection_tasks: "task_properties"
# # mongo_collection_results: "task_results"
# mongo_collection_results: "task_results"
#
# coll_duration_name: "task_durations"
# # coll_risk_name: "task_synergies"
# coll_risk_name: "task_synergies_bayesian"

# ------------------------------------------------------
## VELOCITY SCALING
# mongo_database: "velocity_scaling"
# mongo_collection_tasks: "task_properties"
# mongo_collection_results: "task_results_scaling"
# coll_duration_name: "task_durations"
# # coll_risk_name: "task_synergies"
# coll_risk_name: "task_synergies_bayesian"
# ---------------------------------------------------------
