# mongo_database: "test_mosaic"
# mongo_collection_tasks: "tasks_properties"
# mongo_collection_results: "dummy_results"
# coll_risk_name: "dummy_risks"
# coll_duration_name: "dummy_durations"


mongo_database: "agents_synergy"
mongo_collection_tasks: "tasks_properties"
mongo_collection_results: "sinergy_results"
coll_risk_name: "sinergy_risks"
coll_duration_name: "sinergy_durations"

