# Solver Selection #
optimization:
  # type: human_aware_complete
  # type: base
  type: human_aware_easier
  # type: human_aware_complete
  # type: human_aware_easier_abs

  # type: human_aware_complete
  # type: human_aware_easier
  # type: human_aware_approx
  # type: human_aware_approx_band
  # type: test
  behaviour: continous
  objective: makespan
  n_recipe: 1

  brute_force: false

execution:
  repetitions: 20
  n_recipe: 1





# Problem Info #
# agents_name:
#   - ur5_on_guide
#   - human_right_arm
#
# main_agent: human_right_arm
