group_names_map:
  mg: ur5_on_guide
  mao: human_right_arm

mg:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1
  extend: false
  local_bias: 0.0
  
mao:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 3
  extend: false
  local_bias: 0.0
