controller_list:
  - name: fake_ur5_on_guide_controller
    joints:
      - linear_motor_cursor_joint
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
  - name: fake_human_right_arm_controller
    joints:
      - joint_traslx
      - joint_trasly
      - joint_orientation
      - Belly_rotx
      - Belly_roty
      - jRightShoulder_rotx
      - jRightShoulder_roty
      - jRightShoulder_rotz
      - jRightElbow_rotz
      - jRightWristRoll
      - jRightWristPitch
      - jRightWristYaw
  - name: fake_human_left_arm_controller
    joints:
      - joint_traslx
      - joint_trasly
      - joint_orientation
      - Belly_rotx
      - Belly_roty
      - jLeftShoulder_rotx
      - jLeftShoulder_roty
      - jLeftShoulder_rotz
      - jLeftElbow_rotz