group_names_map:
  dgaco5: ur5_on_guide
  #human_aware: ur10



dgaco5:
  #type: dgaco
  #max_time: 2.0
  #rrt_time: 0.7
  #tree_stall_generation: 3
  #ants_number: 200
  #number_of_nodes: 400
  #ants_stall_generation: 50
  #refinement: true
  #type: dgaco
  #max_time: 1.2
  #rrt_time: 0.8
  #tree_stall_generation: 3
  #ants_number: 200
  #number_of_nodes: 100
  #ants_stall_generation: 50
  #refinement: true

  type: dgaco
  max_time: 10.0
  tree_max_time: 0.8
  tree_stall_generation: 1
  ants_number: 200
  number_of_nodes: 100
  ants_stall_generation: 10
  refinement: true
  tool_frame: tip
  occupancy_weight: 10000

